### ISSUE TITLE
Unknown status 5169 for channel Measurement.Operation.EVeh.ChaStt

### ISSUE THREAD

**Issue by jastBytes** [alengwenus/ha-sma-ev-charger#10]
I recently discovered that sometimes the status for charging_session_status changes to 5169. Haven't found what this means and could not find anything on the internet or the python library defining those constants. As soon as I will see this again, I will look in the WebUI myself to see what it is.

![signal-2023-12-28-133602_002](https://github.com/alengwenus/ha-sma-ev-charger/assets/7187563/3a1a3262-1da1-4460-931e-d25a2dcf6f15)

**Comment by alengwenus** [comment]
Would be great, if you can have a look at this. I checked my logs and the 5169 value never appeared in my setup.

**Comment by jastBytes** [comment]
It is when the car is connected but the charger is locked. The german translation in the UI is "Ladestation gesperrt" the english version "Charging station locked". I would open an PR, but I am currently kind of sick. Will do if I find the time. 👍

**Comment by alengwenus** [comment]
Thanks @jastBytes. I already implemented the session status value if the station is locked.
