### ISSUE TITLE
channel=Parameter.Inverter.WMaxIn vs channel=Parameter.Inverter.WMax

### ISSUE THREAD

**Issue by pcbatterij** [alengwenus/ha-sma-ev-charger#28]
Hello,

When I use the addon as it is with Parameter.Inverter.WMax for the power limit, the EV charger does not change it behaviour. When I change the coding to Parameter.Inverter.WMaxIn then the behaviour of the EV charger changes as expected.

I use version 1.0.13 of the addon
home assitant: 
Core 2024.2.2
Supervisor 2024.02.0
Operating System 11.5
Frontend 20240207.1

EV Charger: EVC22-3AC-10
firmware: 1.2.23.R
Parameter.Chrg.UseEnergyMeter: yes

SMA Energy Meter: SMA home manager 2.0
firmware: 2.13.6.R

**Comment by alengwenus** [comment]
Thanks for reporting @pcbatterij!
Should be fixed in 1.1.1
