### ISSUE TITLE
Error in setup process (config flow)

### ISSUE THREAD

**Issue by adi-ba** [alengwenus/ha-sma-ev-charger#3]
I have the following issue after intalling the HACS integration and trying to add the integration into home assistant.

![image](https://github.com/alengwenus/ha-sma-ev-charger/assets/112014912/368e4c00-2713-4c2c-b2ed-ce3818370c49)

Logger: homeassistant.config_entries
Source: config_entries.py:865
First occurred: 18:29:39 (1 occurrences)
Last logged: 18:29:39

Error occurred loading flow for integration smaev: cannot import name 'DeviceInfo' from 'homeassistant.helpers.device_registry' (/usr/src/homeassistant/homeassistant/helpers/device_registry.py)

**Comment by alengwenus** [comment]
I guess you need to update your Home Assistant version. The DeviceInfo object was moved to device_registry.py in 2023.9. So you should not use any version below that for this integration to work.

**Comment by adi-ba** [comment]
That was it! It works fine now. Thank you! :)
