### ISSUE TITLE
Feature: Allow setting Parameter.Inverter.AcALim

### ISSUE THREAD

**Issue by jastBytes** [alengwenus/ha-sma-ev-charger#5]
I would like to add the feature to set the Parameter.Inverter.AcALim. This way it is possible to control the maximum current the car is charged with giving the ability to have your own smart charging logic instead of the built in one.

Currently I'm using the REST integration to set this parameter according to how much solar power is available. I never coded something for homeassistant, but I think I will be able to provide something quickly.

**Comment by ShaneF1** [comment]
I used to have these two entities visible in my HA instance, but in recent weeks they have been reported by HA as no longer being provided in the entity list. Is this expected?

I recall they were not yet functional but I would benefit greatly from them being visible and functional to provide the capability the OP mentioned.
